//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resepti {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tiedot {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tiedot() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resepti.Tiedot", typeof(Tiedot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.1 kg	Bataatteja (2 kpl)	
        ///400 g	Naudan jauhelihaa	
        ///1	Sipuli hienonnettuna	
        ///2,5 dl	Ruokakerma (maitokin käy)	
        ///1	Kananmuna	
        ///Mustapippuria, suolaa, paprikajauhetta	
        ///Voita	
        ///1 dl	Juustoraastetta.
        /// </summary>
        internal static string ainekset_bataattivuoka {
            get {
                return ResourceManager.GetString("ainekset_bataattivuoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 g	kukkakaalia	
        ///300 g	parsakaalia	
        ///400 g	marinoimattomia broilerinsuikaleita	
        ///1 prk	greme Bonjour cuissine sipulinmaku	
        ///2 dl	kuohukermaa	
        ///voita	
        ///suolaa	
        ///currya	
        ///mustapippuria	
        ///1-2 dl	juustoraastetta.
        /// </summary>
        internal static string ainekset_broilerigratiini {
            get {
                return ResourceManager.GetString("ainekset_broilerigratiini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600 g	Naudanpaistia /voita paistamiseen tai öljyä	
        ///1	Sipuli	
        ///Mustapippuria	
        ///1 tl	Juustokuminaa	
        ///1 tl	Kurmunaa	
        ///3 - 4	Valkosipulinkynttä	
        ///1 tl	Inkivääriä (jauhettua)	
        ///360 g	Valkosipuli-tomaattimurska (Pirkka)	
        ///2 rkl	Jauhettua mantelia	
        ///Suolaa	
        ///Tabackoa muutama tippa ( ehken neljä).
        /// </summary>
        internal static string ainekset_intiapata {
            get {
                return ResourceManager.GetString("ainekset_intiapata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 pss	suikalejuureksia	
        ///600 g	kanafilee suikaleita	
        ///2 dl	3-juuston kerma	
        ///2 dl	ruokakermaa	
        ///2 kpl	kasvis-/kanaliemi kuutiota	
        ///n.6 dl	vettä	
        ///suolaa	
        ///currya.
        /// </summary>
        internal static string ainekset_kanakeitto {
            get {
                return ResourceManager.GetString("ainekset_kanakeitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 dl	keittämätöntä pastaa	
        ///450 g	kanasuikaleita
        ///2,5 dl	Creme Bonjour Cuisine - valkosipuli ja yrtit	
        ///1 kpl	paprika	
        ///1 kpl	iso sipuli	
        ///pippuria	
        ///aromisuolaa	
        ///pizzamaustetta	
        ///.
        /// </summary>
        internal static string ainekset_kanapasta {
            get {
                return ResourceManager.GetString("ainekset_kanapasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 kpl	kesäkurpitsaa	
        ///100 g	raastettua juustoa (mozzarellaa tai edamia)	
        ///1 kpl	kananmuna	
        ///3 rkl	korppujauhoja	
        ///1 rkl	jauhoja	
        ///Tuoretta persiljaa	
        ///Tuoretta basilikaa	
        ///Jauhettua valkosipulia	
        ///Suolaa	
        ///Pippuria	
        ///Chiliä	
        ///3 rkl	korppujauhoja.
        /// </summary>
        internal static string ainekset_kesäpihvit {
            get {
                return ResourceManager.GetString("ainekset_kesäpihvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomaattikastike
        ///Oliiviöljyä	
        ///2 tlk	Kokonaisia tomaatteja tai tomaattimurskaa (Mutti)	
        ///1 dl	Punaviiniä tai punaista vermuttia	
        ///1	Sipuli	
        ///Valkosipulia	
        ///2–3	Porkkanaa	
        ///Tuoretta basilikaa	
        ///Lisäksi
        ///6–10	Lasagnelevyä	
        ///250 g	Mascarpone-juustoa	
        ///250 g	Mozzarellaa	
        ///Parmesaania	
        ///Suolaa, pippuria ja muskottipähkinää.
        /// </summary>
        internal static string ainekset_lasagne {
            get {
                return ResourceManager.GetString("ainekset_lasagne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-7	Tagliatelle-rullaa	
        ///200 g	Chorizo-makkaraa	
        ///2	Tomaattia	
        ///1	Iso sipuli	
        ///5 dl	Kuohukerma	
        ///1 dl	Paseerattua tomaattia	
        ///Suolaa, pippuria ja vähän paprikajauhetta.
        /// </summary>
        internal static string ainekset_lihapasta {
            get {
                return ResourceManager.GetString("ainekset_lihapasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 kpl	perunoita	
        ///1 kpl	parsakaali	
        ///1 kpl	sipuli	
        ///n.2 dl	maissia	
        ///2 kpl	munia	
        ///n.2 dl	kermaa	
        ///n.1 dl	kasvisten keitinlientä
        ///suolaa	
        ///musta-ja valkopippuria myllystä	
        ///savupaprikaa	
        ///oliiviöljyä paistamiseen.
        /// </summary>
        internal static string ainekset_perunavuoka {
            get {
                return ResourceManager.GetString("ainekset_perunavuoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nokare	voita	
        ///1/2	purjoa silputtuna	
        ///pala	juuriselleriä	
        ///1	porkkana	
        ///1	valkosipulin kynsi silputtuna	
        ///1 l	tuoreita kanttarelleja (tai pari pientä rasiaa pakastettuja)	
        ///8 dl	kasvislientä	
        ///200 g	ruohosipulituorejuustoa	
        ///valkopippuria myllystä	
        ///timjamia	
        ///rosmariinia	
        ///2 dl	kermaa	
        ///(maizenan vaaleaa suurustetta tarvittaessa)	
        ///persiljasilppua koristeeksi.
        /// </summary>
        internal static string ainekset_sienikeitto {
            get {
                return ResourceManager.GetString("ainekset_sienikeitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	tuore tai pakastebroileri kokonaisena	
        ///1-2	luomu sitruunaa	
        ///1	( appelsiini )	
        ///2 rkl	oliiviöljyä	
        ///1 tl	suolaa	
        ///maustevoi :
        ///60 g	voita	
        ///3-4	valkosipulin kynttä	
        ///reilusti	rosmariinia, salviaa, ja vähän rakunaa	
        ///2-3 tl	pippuriseosta (suolatonta)	
        ///1 rkl	sitruunan mehua.
        /// </summary>
        internal static string ainekset_sitruunakana {
            get {
                return ResourceManager.GetString("ainekset_sitruunakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 ruukku	Järvikylän Minttua	
        ///1 ruukku	Järvikylän Basilikaa	
        ///1 prk (200 g)	kermaviiliä	
        ///1 dl	korppujauhoja	
        ///1–1½ tl	suolaa	
        ///1 ½ tl	karkeaksi rouhittua mustapippuria	
        ///700 g	naudan jauhelihaa tai naudanpaisti jauhelihaa	
        ///300 g	fetajuustoa	
        ///2 dl	oliiviviipaleita.
        /// </summary>
        internal static string ainekset_yrttipullat {
            get {
                return ResourceManager.GetString("ainekset_yrttipullat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bataattivuoka {
            get {
                object obj = ResourceManager.GetObject("bataattivuoka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap broilerigratiini {
            get {
                object obj = ResourceManager.GetObject("broilerigratiini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intiapata {
            get {
                object obj = ResourceManager.GetObject("intiapata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kanakeitto {
            get {
                object obj = ResourceManager.GetObject("kanakeitto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kanapasta {
            get {
                object obj = ResourceManager.GetObject("kanapasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kasvis {
            get {
                object obj = ResourceManager.GetObject("kasvis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kesäpihvit {
            get {
                object obj = ResourceManager.GetObject("kesäpihvit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lasagne {
            get {
                object obj = ResourceManager.GetObject("lasagne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lihapasta {
            get {
                object obj = ResourceManager.GetObject("lihapasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pese ja kuori bataatit ja leikkaa siivuiksi (puoli senttiä)
        ///
        ///Paista jauheliha voissa ja lisää paiston lopussa sipuli joukkoon kuullottumaan.
        ///
        ///Mausta suolalla, pippurilla ja  paprikalla.
        ///
        ///Laita matalan vuoan pohjalle ensin bataattisiivuja ,heitä ripaus suolaa niille.
        ///
        ///Lisää jauheliha ja pinnalle vielä kerros bataatteja ja ripaus suolaa .
        ///
        ///Vatkaa muna ja ruokakerma tai maito kevyesti keskenään ja lisää bataattien päälle.
        ///
        ///Jos haluat heitä juustoraastetta päälle.
        ///
        ///Paista 220 -200 astetta uunin ke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_bataattivuoka {
            get {
                return ResourceManager.GetString("ohje_bataattivuoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paista pannulla broilerinsuikaleet. Mausta. Laita kaalit ja broilerinsuikaleet vuokaan. Sekoita kerma ja greme ja kaada vuokaan kaalijen ja broilerin päälle. Tarkista maku. Juustoraastetta päälle ja uuniin 200 astetta noin 40 min..
        /// </summary>
        internal static string ohje_broilerigratiini {
            get {
                return ResourceManager.GetString("ohje_broilerigratiini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leikkaa liha kuutioiksi ja ruskista ne voissa tai öljyssä, kahdessa erässä.
        ///
        ///Huuhdo pannu paistokertojen välissä vedellä ja lisää lihojen päälle kasariin,
        ///
        ///mihin siirrät lihat.
        ///
        ///(Itse käytän voita ,ehkä oikea tapa on käyttää tässä öljyä, makuasia.)
        ///
        ///Kuullota suikaleiksi silputtu sipuli vähässä voissa.
        ///
        ///Lissää joukkoon mausteet ,anna kuumeta hetken.
        ///
        ///Lissää lihojen päälle kasariin tomaattimurska ,sipuliseos ja mantelijauhe.
        ///
        ///Murskaa valkosipuli ja lisää joukkoon.
        ///
        ///Mausta suolalla.
        ///
        ///Hauduta  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_intiapata {
            get {
                return ResourceManager.GetString("ohje_intiapata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruskista kanasuikaleet pannulla.
        ///Laita kattilaan vesi, juurekset, kasvis-/kanaliemi, suola ja anna kiehua.
        ///Kun kasvikset ovat melkein kypsiä lisää joukkoon kermat sekä Currya tuomaan kaunis väri liemelle. Anna kiehua kunnes juurekset ovat kypsyneet.
        ///Tämän jälkeen lisää kana ja anna kiehua vielä hetki..
        /// </summary>
        internal static string ohje_kanakeitto {
            get {
                return ResourceManager.GetString("ohje_kanakeitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keitä pasta. Leikkaa samalla sipuli pieneksi ja kuullota paistinpannulla. Lisää joukkoon kana ja pienen hetken päästä kuutioitu paprika. Paista niin kauan, että kanat ovat kypsiä. Lisää joukkoon Creme Bonjour ja mausteet. Sekoita tasaisesksi ja anna lämmetä muutama minuutti. Lisää lopuksi pannulle keitetty pasta ja sekoita se kastikkeen sisään. .
        /// </summary>
        internal static string ohje_kanapasta {
            get {
                return ResourceManager.GetString("ohje_kanapasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 pihviä:
        ///
        ///Raaska ohueksi kesäkurpitsat.
        ///
        ///Siirrä ne isoon siivilään suolan kanssa ja anna lepää noin 30min painon alla niin että nesteet valuvat pois.
        ///
        ///Purista kesäkurpitsat vielä käsin ja siirrä ne kulhoon, juustoraasteen, kananmunan, persiljan, basilikan, valkosipulin , chilin, suolan ja pippurin kanssa.
        ///
        ///Lisää vielä jauhot ja korppujauhot.
        ///
        ///Sekoita kunnolla kaikki käsillä ja muotoile pihvejä. Jos taikina tuntuu liaan löysältä lisää korppujauhoja.
        ///
        /// 
        ///
        ///Sekoita lautasessa korppujauhoa ja suola [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_kesäpihvit {
            get {
                return ResourceManager.GetString("ohje_kesäpihvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valmista ensin tomaattikastike. Pilko sipuli hienoksi, siivuta valkosipulia maun mukaan ja raasta porkkanat. Kuullota sipuleita muutama minuutti matalalla lämmöllä oliiviöljyssä. Lisää porkkanaraaste sekä viini ja keitä melko tiiviiksi mössöksi. Lisää tomaatit/tomaattimurska. Täytä molemmat tomaattitölkit puolilleen vettä ja huuhtaise niiden avulla viimeisetkin tomaattimehut tölkeistä kastikkeeseen. Lisää maun mukaan suolaa ja mustapippuria sekä basilikaa.
        ///
        ///Anna hautua miedolla lämmöllä vähintään puoli tu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_lasagne {
            get {
                return ResourceManager.GetString("ohje_lasagne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuutioi sipuli pieneksi silpuksi, tomaatit suuremmiksi kuutioiksi, ja Chorizo-makkara puolen sentin paksuisiin siivuihin
        ///Kuullota sipulit vain hetken aikaa tilkassa öljyä
        ///Lisää sekaan kuutioidut tomaatit, paista ja samalla painele tomaatteja niin, että niiden koostumus hajoaa ja niistä irtoaa tomaatin mehua joukkoon
        ///Heitä sekaan Chorizot, ja paista vaan pari minuuttia
        ///Kaada joukkoon kuohukerma, paseerattu tomaatti ja heitä sekaan tagliatellerullat
        ///Anna hiljalleen porista kannen alla ensin n. 3 minuutti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_lihapasta {
            get {
                return ResourceManager.GetString("ohje_lihapasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuori ja keitä perunat suolalla maustetussa vedessä lähes kypsiksi ja nosta jäähtymään leikkuulaudalle, älä heitä keitinvettä pois vaan kypsennä siinä myös parsakaali. Kuori ja viipaloi sipuli, ota maissit johonkin esille. Viipaloi/kuutioi perunat ja parsakaalit miten haluat. Omat perunat oli yleislajiketta, kiinteät olisi ollut parempia mutta hyvin nämäkin menivät.
        ///
        ///Paista perunat ja sipulit sopivassa määrässä oliiviöljyä, lisää parsakaalit ja mausta makusi mukaan suolalla ja pippureilla ja jos tykkäät n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_perunavuoka {
            get {
                return ResourceManager.GetString("ohje_perunavuoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuumenna pannulla voi, kuullota siinä huuhdeltu ja silputtu purjo, valkosipuli, tulitikun hienoksi leikattu porkkana ja selleri. Lisää pieneksi kuutioidut sienet.
        ///
        ///Sekoittele jonkin aikaa ja lisää kasvisliemi. Anna muhia hiljalleen n. 30 min.
        ///
        ///Lisää tuorejuusto ja mausteet sekä kerma. Anna muhia vielä niin että saostuu. Lisää tarvittaessa Maizena-suurustetta. Tarkista maku ja lisää tarvittaessa yrttisuolaa. Viimeistele persiljasilpulla ja tarjoa tuoreen leivän kanssa.
        ///
        ///Jos käytät tuoreita sieniä, kuul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_sienikeitto {
            get {
                return ResourceManager.GetString("ohje_sienikeitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maustevoi:
        ///Sekoita pehmeään voihin raastettu sitruunankuori, puserretut valkosipulin kynnet ja mausteet.
        ///Valmistus:
        ///Laita uuni lämpenemään 200 asteeseen.   Jos käytät pakastebroileria, sulata se jääkaapissa yön yli. (pakkauksen ohjeen mukaan). Huuhtele broileri ja kuivaa huolellisesti, näin saat rapean pinnan. Laita maustevoita broilerin nahan ja lihan väliin tasaisesti jokapuolelle. Hiero broilerin pintaan öljy, 1/2 sitruunan mehu suolaa ja loput maustevoit sekä pippurisekoitusta.  Laita broilerin sisää [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ohje_sitruunakana {
            get {
                return ResourceManager.GetString("ohje_sitruunakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekoita silputut yrtit, kermaviili, kananmuna, korppujauhot, suola ja pippuri. Anna turvota 15 minuuttia. Lisää jauheliha, murustettu fetajuusto ja oliiviviipaleet. Pyörittele mureketaikina pulliksi ja paista joko uunissa tai paistinpannussa..
        /// </summary>
        internal static string ohje_yrttipullat {
            get {
                return ResourceManager.GetString("ohje_yrttipullat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perunavuoka {
            get {
                object obj = ResourceManager.GetObject("perunavuoka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pihvi {
            get {
                object obj = ResourceManager.GetObject("pihvi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sienikeitto {
            get {
                object obj = ResourceManager.GetObject("sienikeitto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sitruunakana {
            get {
                object obj = ResourceManager.GetObject("sitruunakana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yrttipullat {
            get {
                object obj = ResourceManager.GetObject("yrttipullat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
